name: Python application

on:
  workflow_dispatch: 
  
permissions:
  contents: read
  
jobs:
  build:

    runs-on: [self-hosted,fastapi-server]

    steps:
    - name: check out the code
      uses: actions/checkout@v4
      
    - name: setup python 
      run: |
        sudo apt install python3 -y
        sudo apt install python3.12-venv -y
        sudo apt install python3-pip -y
        python3  -m venv venv
        source ./venv/bin/activate
        pip install -r requirements.txt
    - name: start application
      run: |
       sudo systemctl start myapp
       echo "application will be started after getting idea about the path"
  
